version: "3.8"

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.3.5
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./ssl/server.crt:/etc/https/tls.crt
      - ./ssl/server.key:/etc/https/tls.key
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloakpass
      KC_HOSTNAME: 10.1.1.39
      KC_HTTP_PORT: 8080
      KC_HTTPS_PORT: 8443
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      # KC_HTTPS_CERTIFICATE_FILE: /etc/https/tls.crt
      # KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/https/tls.key
    networks:
      - keycloak_network
    command:
      - "start"

networks:
  keycloak_network:
    external: true
